# Generated by Django 4.1.1 on 2023-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0017_cvd_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='facilitator_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
